### ISSUE TITLE
what configs should be setted in rviz to get scene.png

### ISSUE THREAD

**Issue by hwscut** [berndpfrommer/tagslam_test#1]
when running the test 11, I can run the whole codes successfully. but I cannot get the same scene.png.
so I wonder how to config my rviz. 
Or can you provide a rviz config file?

**Comment by berndpfrommer** [comment]
Here is a rviz file that will produce the visualization:
[tagslam.rviz.gz](https://github.com/berndpfrommer/tagslam_test/files/3628695/tagslam.rviz.gz)

However, there are a few more steps involved to get the graph.
1) modify "test.launch" and set the exit_when_done flag to false:
`<param name="exit_when_done" value="false"/>`
2) After tagslam has finished, leave the node running, and from another terminal:
`rosservice call /tagslam/replay`

The last step will replay the odometry at a slow enough speed such that rviz can draw it.

**Comment by hwscut** [comment]
thanks,  this rviz has fixed my problem.
