### ISSUE TITLE
Trouble extracting the data in tests folder

### ISSUE THREAD

**Issue by ArghyaChatterjee** [berndpfrommer/tagslam_test#4]
Hello,
First of all, wonderful work. 
I am trying to extract the data inside the tests folder (test1, test2, ...). For some reason, when I try to extract the files using right click --> extract here, the `reference.bag.bz2` file creates a file named `data` without any extension and `tag_detections.bag.bz2` file creates nothing. Is there any particular way to extract these files (command line or something similar).
My OS & ROS Version: Ubuntu 18.04 and ROS Melodic

![Screenshot from 2021-10-18 18-38-05](https://user-images.githubusercontent.com/28845357/137732179-e779f4e2-c2dc-4704-8e11-a2b9dbd6638e.png)

**Comment by berndpfrommer** [comment]
I think I pushed some script recently. Does this one work for you?

https://github.com/berndpfrommer/tagslam_test/blob/master/src/uncompress_bags.bash
